/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/grid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeploygridGrid"];
                    };
                };
                /** @description Error */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MuxError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        DeploygridComponent: {
            children?: components["schemas"]["DeploygridComponent"][] | null;
            component_type?: string;
            deployments?: {
                [key: string]: components["schemas"]["DeploygridDeployment"];
            } | null;
            name?: string;
        };
        DeploygridDeployment: {
            version?: string;
        };
        DeploygridEnvironment: {
            name?: string;
        };
        DeploygridGrid: {
            components?: components["schemas"]["DeploygridComponent"][] | null;
            environments?: components["schemas"]["DeploygridEnvironment"][] | null;
        };
        MuxError: {
            error?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
