/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/grid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Grid of the first System; kept for v1 compatibility. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeploygridGrid"];
                    };
                };
                /** @description Error */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MuxError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/observations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Collector push. Authenticate with a bearer token issued for one Cluster; a snapshot replaces the listed kinds, otherwise resources are upserted and removed incrementally. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["DeploygridObservation"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeploygridObservationResponse"];
                    };
                };
                /** @description Error */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MuxError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/systems": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List systems. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeploygridSystemList"];
                    };
                };
                /** @description Error */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MuxError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/systems/{system}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get one system with its environments and groups. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    system: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeploygridSystem"];
                    };
                };
                /** @description Error */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MuxError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/systems/{system}/components": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description All component rows of the system, flattened. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    system: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeploygridGridRowList"];
                    };
                };
                /** @description Error */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MuxError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/systems/{system}/components/{component}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description One component row with its cells. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    system: string;
                    component: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeploygridGridRow"];
                    };
                };
                /** @description Error */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MuxError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/systems/{system}/components/{component}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Version changes of one component, newest first. */
        get: {
            parameters: {
                query?: {
                    environment?: string;
                    /** @description RFC 3339 timestamp */
                    since?: string;
                    limit?: number;
                };
                header?: never;
                path: {
                    system: string;
                    component: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ControllerHistoryList"];
                    };
                };
                /** @description Error */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MuxError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/systems/{system}/configurations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Configuration names of the system and the environments that override them. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    system: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeploygridConfigurationList"];
                    };
                };
                /** @description Error */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MuxError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/systems/{system}/configurations/{configuration}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Merged values of one configuration; environment documents deep-merge over the system-wide one. */
        get: {
            parameters: {
                query?: {
                    environment?: string;
                };
                header?: never;
                path: {
                    system: string;
                    configuration: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeploygridConfigurationValues"];
                    };
                };
                /** @description Error */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MuxError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/systems/{system}/grid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The grid: ordered groups of component rows with one cell per environment. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    system: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeploygridGrid"];
                    };
                };
                /** @description Error */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MuxError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/systems/{system}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Version changes across the system, newest first. */
        get: {
            parameters: {
                query?: {
                    environment?: string;
                    /** @description RFC 3339 timestamp */
                    since?: string;
                    limit?: number;
                };
                header?: never;
                path: {
                    system: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ControllerHistoryList"];
                    };
                };
                /** @description Error */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MuxError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/systems/{system}/unassigned": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Observed resources that matched no component. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    system: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeploygridArtifactList"];
                    };
                };
                /** @description Error */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MuxError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/systems/{system}/views": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Views of the system with template validity. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    system: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeploygridViewList"];
                    };
                };
                /** @description Error */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MuxError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/systems/{system}/views/{view}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Render a view for an environment; the response carries the view's content type. */
        get: {
            parameters: {
                query?: {
                    environment?: string;
                };
                header?: never;
                path: {
                    system: string;
                    view: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
                /** @description Error */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MuxError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ControllerHistoryList: {
            items?: components["schemas"]["HistoryChange"][] | null;
        };
        DeploygridArtifact: {
            cluster?: string;
            environment?: string;
            health?: string;
            kind?: string;
            name?: string;
            namespace?: string;
            versions?: components["schemas"]["DeploygridVersion"][];
        };
        DeploygridArtifactList: {
            items?: components["schemas"]["DeploygridArtifact"][] | null;
        };
        DeploygridCell: {
            artifacts?: components["schemas"]["DeploygridArtifact"][];
            cluster?: string;
            clusters?: string[];
            desired_version?: string;
            drifted?: boolean;
            health?: string;
            hosts?: string[];
            inconsistent?: boolean;
            links?: components["schemas"]["DeploygridLink"][];
            namespace?: string;
            version?: string;
        };
        DeploygridComponentRef: {
            description?: string;
            discovered?: boolean;
            display_name?: string;
            kind?: string;
            name?: string;
        };
        DeploygridConfigurationInfo: {
            environments?: string[] | null;
            name?: string;
            system_wide?: boolean;
        };
        DeploygridConfigurationList: {
            items?: components["schemas"]["DeploygridConfigurationInfo"][] | null;
        };
        DeploygridConfigurationValues: {
            environment?: string;
            name?: string;
            values?: unknown;
        };
        DeploygridEnvironment: {
            display_name?: string;
            name?: string;
        };
        DeploygridGrid: {
            environments?: components["schemas"]["DeploygridEnvironment"][] | null;
            errors?: string[];
            groups?: components["schemas"]["DeploygridGridGroup"][] | null;
            system?: components["schemas"]["DeploygridSystem"];
            warnings?: string[];
        };
        DeploygridGridGroup: {
            display_name?: string;
            name?: string;
            rows?: components["schemas"]["DeploygridGridRow"][] | null;
        };
        DeploygridGridRow: {
            cells?: {
                [key: string]: components["schemas"]["DeploygridCell"];
            } | null;
            children?: components["schemas"]["DeploygridGridRow"][];
            component?: components["schemas"]["DeploygridComponentRef"];
        };
        DeploygridGridRowList: {
            items?: components["schemas"]["DeploygridGridRow"][] | null;
        };
        DeploygridGroup: {
            display_name?: string;
            name?: string;
        };
        DeploygridLink: {
            name?: string;
            url?: string;
        };
        DeploygridObservation: {
            cluster?: string;
            errors?: string[];
            heartbeat?: components["schemas"]["DeploygridObservationHeartbeat"];
            kinds?: string[];
            removed?: components["schemas"]["RepositoryResource"][];
            resources?: components["schemas"]["RepositoryResource"][];
            snapshot?: boolean;
        };
        DeploygridObservationHeartbeat: {
            collector_version?: string;
            kubernetes_version?: string;
            /** Format: date-time */
            sent_at?: string;
        };
        DeploygridObservationResponse: {
            accepted?: number;
            cluster?: string;
            resync?: boolean;
        };
        DeploygridSystem: {
            description?: string;
            display_name?: string;
            environments?: components["schemas"]["DeploygridEnvironment"][] | null;
            groups?: components["schemas"]["DeploygridGroup"][];
            name?: string;
        };
        DeploygridSystemList: {
            items?: components["schemas"]["DeploygridSystem"][] | null;
        };
        DeploygridVersion: {
            desired?: string;
            image?: string;
            kind?: string;
            name?: string;
            value?: string;
        };
        DeploygridViewInfo: {
            configuration?: string;
            content_type?: string;
            display_name?: string;
            error?: string;
            name?: string;
            valid?: boolean;
        };
        DeploygridViewList: {
            items?: components["schemas"]["DeploygridViewInfo"][] | null;
        };
        HistoryChange: {
            cluster?: string;
            component?: string;
            desired?: string;
            environment?: string;
            from?: string;
            health?: string;
            namespace?: string;
            /** Format: date-time */
            observed_at?: string;
            system?: string;
            to?: string;
        };
        MuxError: {
            error?: string;
        };
        RepositoryClusterLocation: {
            name?: string;
            namespace?: string;
            server?: string;
        };
        RepositoryComponent: {
            image?: string;
            kind?: string;
            name?: string;
            version?: string;
        };
        RepositoryResource: {
            annotations?: {
                [key: string]: string;
            };
            chartVersion?: string;
            components?: components["schemas"]["RepositoryComponent"][];
            desiredVersion?: string;
            destination?: components["schemas"]["RepositoryClusterLocation"];
            health?: string;
            hosts?: string[];
            kind?: string;
            labels?: {
                [key: string]: string;
            };
            name?: string;
            namespace?: string;
            objectName?: string;
            parent?: string;
            syncRevision?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
