// Code generated by mockery v2.46.3. DO NOT EDIT.

package mock_service

import (
	context "context"

	deploygrid "github.com/activatedio/deploygrid/pkg/deploygrid"
	mock "github.com/stretchr/testify/mock"
)

// GridService is an autogenerated mock type for the GridService type
type GridService struct {
	mock.Mock
}

type GridService_Expecter struct {
	mock *mock.Mock
}

func (_m *GridService) EXPECT() *GridService_Expecter {
	return &GridService_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx
func (_m *GridService) Get(ctx context.Context) (*deploygrid.Grid, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *deploygrid.Grid
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*deploygrid.Grid, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *deploygrid.Grid); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*deploygrid.Grid)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GridService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type GridService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
func (_e *GridService_Expecter) Get(ctx interface{}) *GridService_Get_Call {
	return &GridService_Get_Call{Call: _e.mock.On("Get", ctx)}
}

func (_c *GridService_Get_Call) Run(run func(ctx context.Context)) *GridService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *GridService_Get_Call) Return(_a0 *deploygrid.Grid, _a1 error) *GridService_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GridService_Get_Call) RunAndReturn(run func(context.Context) (*deploygrid.Grid, error)) *GridService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewGridService creates a new instance of GridService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGridService(t interface {
	mock.TestingT
	Cleanup(func())
}) *GridService {
	mock := &GridService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
