# permissions for end users to edit metadataviews.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: tmp
    app.kubernetes.io/managed-by: kustomize
  name: metadataview-editor-role
rules:
- apiGroups:
  - deploygrid.activated.io.activated.io
  resources:
  - metadataviews
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deploygrid.activated.io.activated.io
  resources:
  - metadataviews/status
  verbs:
  - get
