---
apiVersion: v1
kind: Namespace
metadata:
  name: stage-app-a
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: stage-app-a
  name: app
  labels:
    app.kubernetes.io/name: stage-app-a
    helm.sh/chart: sealed-secrets-1.16.1
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: stage-app-a
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: stage-app-a
  name: app-side
  labels:
    app.kubernetes.io/name: stage-app-a
    helm.sh/chart: sealed-secrets-1.16.1
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: stage-app-a
spec:
  selector:
    matchLabels:
      app: nginx-side
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-side
    spec:
      containers:
      - name: nginx-side
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Namespace
metadata:
  name: stage-app-b
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: stage-app-b
  name: app
  labels:
    app.kubernetes.io/name: stage-app-b
    helm.sh/chart: sealed-secrets-1.16.1
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: stage-app-b
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: stage-app-b
  name: app-side
  labels:
    app.kubernetes.io/name: stage-app-b
    helm.sh/chart: sealed-secrets-1.16.1
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: stage-app-b
spec:
  selector:
    matchLabels:
      app: nginx-side
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-side
    spec:
      containers:
      - name: nginx-side
        image: nginx:1.14.2
        ports:
        - containerPort: 80
