apiVersion: deploygrid.activated.io.activated.io/v1alpha1
kind: MetadataView
metadata:
  labels:
    app.kubernetes.io/name: tmp
    app.kubernetes.io/managed-by: kustomize
  name: metadataview-sample
spec:
  # TODO(user): Add fields here
