{{- if and .Values.token (not .Values.existingSecret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "deploygrid-collector.tokenSecretName" . }}
  labels:
    {{- include "deploygrid-collector.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.existingSecret.key }}: {{ .Values.token | quote }}
{{- end }}
