---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: systems.deploygrid.activated.io
spec:
  group: deploygrid.activated.io
  names:
    kind: System
    plural: systems
    singular: system
  preserveUnknownFields: false
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                description:
                  nullable: true
                  type: string
                displayName:
                  nullable: true
                  type: string
                environments:
                  items:
                    properties:
                      description:
                        nullable: true
                        type: string
                      displayName:
                        nullable: true
                        type: string
                      name:
                        nullable: true
                        type: string
                    type: object
                  nullable: true
                  type: array
              type: object
            status:
              type: object
          type: object
      served: true
      storage: true

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: metadatas.deploygrid.activated.io
spec:
  group: deploygrid.activated.io
  names:
    kind: Metadata
    plural: metadatas
    singular: metadata
  preserveUnknownFields: false
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                foo:
                  nullable: true
                  type: string
              type: object
            status:
              type: object
          type: object
      served: true
      storage: true

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: metadatas.deploygrid.activated.io
spec:
  group: deploygrid.activated.io
  names:
    kind: Metadata
    plural: metadatas
    singular: metadata
  preserveUnknownFields: false
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                foo:
                  nullable: true
                  type: string
              type: object
            status:
              type: object
          type: object
      served: true
      storage: true

