---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "deploygird.fullname" . }}
  labels:
    {{- include "deploygird.labels" . | nindent 4 }}
data:
  config.yaml: |-
    {{- if .Values.clusters }}
    clusters:
      {{- with .Values.clusters }}
      - name: {{ .name }}
        address: {{ .address }}
        {{- if .local }}
        local: true
        {{- end }}
        {{- if .kubeconfigSecretName }}
        kubeConfigPath: /etc/clusters/{{ .name }}/config.yaml
        {{- end }}
      {{- end }}
    {{- end }}

