---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "deploygrid.fullname" . }}
  labels:
    {{- include "deploygrid.labels" . | nindent 4 }}
data:
  config.yaml: |-
    control:
      enabled: {{ .Values.control.enabled }}
      namespace: {{ .Release.Namespace }}
    {{- with .Values.sources.applicationKinds }}
    sources:
      applicationKinds:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- if .Values.clusters }}
    clusters:
      {{- if .Values.environments }}
      environments:
      {{- range .Values.environments }}
        - {{ . }}
      {{- end }}
      {{- end }}
      clusters:
        {{- range .Values.clusters }}
        - name: {{ .name }}
          {{- if .address }}
          address: {{ .address }}
          {{- end }}
          {{- if .mode }}
          mode: {{ .mode }}
          {{- end }}
          {{- if .local }}
          local: true
          {{- end }}
          {{- if .kubeconfigSecretName }}
          kubeConfigPath: /etc/clusters/{{ .name }}/config.yaml
          {{- end }}
        {{- end }}
    {{- end }}

