---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "deploygrid.fullname" . }}
  labels:
    {{- include "deploygrid.labels" . | nindent 4 }}
data:
  config.yaml: |-
    {{- if .Values.clusters }}
    clusters:
      clusters:
        {{- range .Values.clusters }}
        - name: {{ .name }}
          {{- if .address }}
          address: {{ .address }}
          {{- end }}
          {{- if .local }}
          local: true
          {{- end }}
          {{- if .kubeconfigSecretName }}
          kubeConfigPath: /etc/clusters/{{ .name }}/config.yaml
          {{- end }}
        {{- end }}
    {{- end }}

