# START CRD {{- if .Values.crds.enabled }}
./crds
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # START ANNOTATIONS {{- if .Values.crds.keep }}
  annotations:
    helm.sh/resource-policy: keep
  # END ANNOTATIONS {{- end }}

  labels:
    app: '{{ template "deploygrid.name" . }}'
    # Generated Labels {{- include "labels" . | nindent 4 }}

    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/name: '{{ template "deploygrid.name" . }}'
spec:
  group: ""
  names:
    kind: ""
    plural: ""
  scope: ""
  versions: null

# END CRD {{- end }}
