apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "deploygrid.fullname" . }}
  labels:
    {{- include "deploygrid.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "deploygrid.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "deploygrid.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "deploygrid.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-api
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          env:
            - name: CONFIG_PATH
              value: /etc/deploygrid/config.yaml
            - name: SERVER_HOST
              value: 0.0.0.0
          ports:
            - name: http-api
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/healthz
              port: http-api
          readinessProbe:
            httpGet:
              path: /api/healthz
              port: http-api
          volumeMounts:
            - name: config
              mountPath: "/etc/deploygrid"
          {{- range .Values.clusters }}
          {{- if .kubeconfigSecretName }}
            - name: cluster-{{ .name }}
              mountPath: "/etc/clusters/{{ .name }}"
          {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: {{ .Chart.Name }}-ui
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.ui.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
          ports:
            - name: http-ui
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http-ui
          readinessProbe:
            httpGet:
              path: /
              port: http-ui
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "deploygrid.fullname" . }}
        {{- range .Values.clusters }}
        {{- if .kubeconfigSecretName }}
        - name: cluster-{{ .name }}
          secret:
            secretName: {{ .kubeconfigSecretName }}
        {{- end }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
