apiVersion: v1
kind: Service
metadata:
  name: {{ include "deploygrid.fullname" . }}
  labels:
    {{- include "deploygrid.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http-api
    - port: {{ .Values.ui.service.port }}
      targetPort: 80
      protocol: TCP
      name: http-ui
  selector:
    {{- include "deploygrid.selectorLabels" . | nindent 4 }}
