name: Test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  test:
    strategy:
      matrix:
        runner: [custom-ubuntu-24.04, custom-ubuntu-24.04-arm]
    runs-on: ${{ matrix.runner }}
    steps:
    - uses: actions/checkout@v4

    - name: Create k8s Kind Cluster
      working-directory: ./api
      run: |
        ./kind/setup.sh
      post: |
        ./kind/teardown.sh

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.3'

    - name: Test
      working-directory: ./api
      run: |
        go test -v ./...

