name: Test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  test:
    strategy:
      matrix:
        runner: [custom-ubuntu-24.04, custom-ubuntu-24.04-arm]
    runs-on: ${{ matrix.runner }}
    steps:
    - uses: actions/checkout@v4

    - name: Create k8s Kind Cluster
      uses: helm/kind-action@v1
      with:
        cluster_name: kind
        config: ./kind/kind-cluster.yaml

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.2'

    - name: Test
      run: |
        go test -v ./...

